controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_hand_controller
    joints:
      []
initial:
  - group: arm
    pose: home